name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: rbcs399registry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker image build --pull --file './Dockerfile' --tag 'fileserverservice:latest' --label 'com.microsoft.created-by=visual-studio-code' --platform 'linux/amd64' './'
        docker tag fileserverservice rbcs399registry.azurecr.io/fileserverservice:latest
        docker push rbcs399registry.azurecr.io/fileserverservice:latest
